const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway.",
    Image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b",
    price: 1500,
    location: "Malibu",
    Country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment.",
    Image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    price: 1200,
    location: "New York City",
    Country: "United States",
  },
  {
    title: "Rustic Mountain Cabin",
    description: "Enjoy a peaceful retreat in this cozy mountain cabin.",
    Image: "https://images.unsplash.com/photo-1448375240586-882707db888b",
    price: 900,
    location: "Aspen",
    Country: "United States",
  },
  {
    title: "Luxury Penthouse Suite",
    description: "Experience luxury in this high-end penthouse suite.",
    Image: "https://images.unsplash.com/photo-1554995207-c18c203602cb",
    price: 3000,
    location: "Los Angeles",
    Country: "United States",
  },
  {
    title: "Seaside Villa",
    description: "Enjoy the beach view in this elegant seaside villa.",
    Image: "https://images.unsplash.com/photo-1560184897-9d5cfd3dd0b6",
    price: 1800,
    location: "Miami",
    Country: "United States",
  },
  {
    title: "Lakeview Cottage",
    description: "Perfect getaway by the serene lakeside.",
    Image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7",
    price: 1000,
    location: "Lake Tahoe",
    Country: "United States",
  },
  {
    title: "Urban Studio Apartment",
    description: "Modern and compact studio in the city center.",
    Image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    price: 700,
    location: "Chicago",
    Country: "United States",
  },
  {
    title: "Desert Retreat",
    description: "Unwind in this spacious desert retreat.",
    Image: "https://images.unsplash.com/photo-1522152302421-8fdc3b8c1b27",
    price: 1100,
    location: "Phoenix",
    Country: "United States",
  },
  {
    title: "Countryside Farmhouse",
    description: "Enjoy a rural escape in this charming farmhouse.",
    Image: "https://images.unsplash.com/photo-1578916171728-61d1ce37cf4b",
    price: 800,
    location: "Nashville",
    Country: "United States",
  },
  {
    title: "Snowy Mountain Chalet",
    description: "Cozy up in this warm and stylish mountain chalet.",
    Image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 2000,
    location: "Denver",
    Country: "United States",
  },
  {
    title: "Coastal Bungalow",
    description: "Relax in this peaceful coastal bungalow.",
    Image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    price: 1300,
    location: "Santa Monica",
    Country: "United States",
  },
  {
    title: "Forest Treehouse",
    description: "Stay amidst nature in this stunning treehouse.",
    Image: "https://images.unsplash.com/photo-1573566472937-df473c58da62",
    price: 950,
    location: "Portland",
    Country: "United States",
  },
  {
    title: "Historic Mansion",
    description: "Step back in time with this beautifully restored mansion.",
    Image: "https://images.unsplash.com/photo-1598188303589-18b0ff3f6a87",
    price: 2800,
    location: "Boston",
    Country: "United States",
  },
  {
    title: "Tropical Paradise Resort",
    description: "Experience island life in this tropical paradise.",
    Image: "https://images.unsplash.com/photo-1518709268803-4f7b2091db58",
    price: 3200,
    location: "Honolulu",
    Country: "United States",
  },
  {
    title: "Suburban Family Home",
    description: "Perfect family vacation home in a quiet suburb.",
    Image: "https://images.unsplash.com/photo-1600585154356-1e672ccec062",
    price: 1600,
    location: "Orlando",
    Country: "United States",
  }
];
module.exports = {data:sampleListings};
